_wandb:
    value:
        cli_version: 0.25.0
        e:
            rwzajltatxykvembv30yx5z8maxu7765:
                codePath: projects/new_model-Copy/aux_train.py
                codePathLocal: aux_train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1081101176832"
                        used: "666370977792"
                email: miskoweis1@gmail.com
                executable: /home/misko/miniconda3/envs/radiate/bin/python
                git:
                    commit: 4866f40151fd0d6665115b57a8aa0ac6187812b6
                    remote: https://github.com/MichalWeis/BP.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-2bf95723-1a71-40ae-8b13-5959780e8c06
                host: PC-MISO
                memory:
                    total: "33508417536"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/misko/projects/BP/projects/new_model-Copy/aux_train.py
                python: CPython 3.10.12
                root: /home/misko/projects/BP/projects/new_model-Copy
                startedAt: "2026-04-28T12:27:28.087498Z"
                writerId: rwzajltatxykvembv30yx5z8maxu7765
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
backbone_checkpoint:
    value: /home/misko/projects/BP/projects/new_model/checkpoints/scheduler_Tmax/epoch_0100.pt
balanced_counts:
    value:
        clear: 1000
        fog: 1000
        rain: 700
        snow: 1000
batch_size:
    value: 16
focal_alpha:
    value:
        clear: 0.953464150428772
        fog: 0.953464150428772
        rain: 1.139607548713684
        snow: 0.953464150428772
learning_rate:
    value: 0.001
max_per_class:
    value: 1000
num_epochs:
    value: 60
rain_target:
    value: 700
task:
    value: auxiliary_head_only
weather_focal_gamma:
    value: 2
weight_decay:
    value: 0.0005
